version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_server
    environment:
    # root user: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
      # MYSQL_USER: user
      # MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: