apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
  namespace: ecommerce-ns
spec:
  selector:
    app: ecommerce-backend-deployment
    type: backend
    technology: spring-boot
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 80
  type: NodePort