apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend-deployment
  namespace: ecommerce-ns
  labels:
    app: ecommerce-backend
    type: backend
    technology: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
      type: backend
      technology: spring-boot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: ecommerce-backend-pod
      labels:
        app: ecommerce-backend
        type: backend
        technology: spring-boot
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: ecommerce-backend-container
          image: marcusvbrangel/ecommerce-backend:1.0.9
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
#            readOnlyRootFilesystem: true
          ports:
            - containerPort: 80
              protocol: TCP
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: prod
          envFrom:
            - configMapRef:
                name: ecommerce-backend-configmap
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.3"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 80
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 80
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            successThreshold: 2
#            failureThreshold: 3
#          startupProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 80
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            successThreshold: 1
#            failureThreshold: 3












