apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-postgres-pv
  namespace: ecommerce-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ecommerce-postgres
