apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-postgres-deployment
  namespace: ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-postgres
  template:
    metadata:
      labels:
        app: ecommerce-postgres
    spec:
      containers:
        - name: ecommerce-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ecommerce-postgres-configmap
#            - secretRef:
#                name: ecommerce-postgres-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: ecommerce-postgres-pvc
