apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-postgres-configmap
  namespace: ecommerce-ns
data:
  POSTGRES_DNS: "ecommerce-postgres-service"
  POSTGRES_DB: "spring-ecommerce-prod"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "1234"